-- MySQL Script generated by MySQL Workbench
-- Thu Aug 27 12:14:49 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Proyecto_sena
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Proyecto_sena
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Proyecto_sena` DEFAULT CHARACTER SET utf8 ;
USE `Proyecto_sena` ;

-- -----------------------------------------------------
-- Table `Proyecto_sena`.`PROGRAMAFORMACION`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Proyecto_sena`.`PROGRAMAFORMACION` (
  `Id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `FechaRegistro` DATE NOT NULL,
  `NumeroFicha` INT NOT NULL,
  `FechaInicio` DATE NOT NULL,
  `FechaFinalizacion` DATE NOT NULL,
  `NombrePrograma` VARCHAR(200) NOT NULL,
  `NivelPrograma` ENUM('Operario', 'Tecnico', 'Tecnologo', 'ESpecializacion tecnologica') NOT NULL,
  PRIMARY KEY (`Id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Proyecto_sena`.`PERSONA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Proyecto_sena`.`PERSONA` (
  `Documento` INT NOT NULL,
  `Nombre` VARCHAR(50) NOT NULL,
  `Apellido` VARCHAR(50) NOT NULL,
  `Telefono` INT UNSIGNED NOT NULL,
  `Correo` VARCHAR(45) NOT NULL,
  `Rol` ENUM('Funcionario', 'Aprendiz', 'Pasante') NOT NULL,
  `Contraseña` VARCHAR(50) NOT NULL,
  `Programaformacion` INT NOT NULL,
  `Estado` ENUM('Activo', 'Inactivo') NOT NULL,
  INDEX `fk_PERSONA_PROGRAMAFORMACION1_idx` (`Programaformacion` ASC),
  PRIMARY KEY (`Documento`),
  CONSTRAINT `fk_PERSONA_PROGRAMAFORMACION1`
    FOREIGN KEY (`Programaformacion`)
    REFERENCES `Proyecto_sena`.`PROGRAMAFORMACION` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Proyecto_sena`.`PRESTAMO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Proyecto_sena`.`PRESTAMO` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `FechaPrestamo` DATETIME NOT NULL,
  `FechaEntrega` DATETIME NOT NULL,
  `Observaciones` VARCHAR(200) NOT NULL,
  `Estado` ENUM('Activo', 'Inactivo') NOT NULL,
  `Responsable` INT NOT NULL,
  PRIMARY KEY (`Id`),
  INDEX `fk_PRESTAMO_PERSONA1_idx` (`Responsable` ASC),
  CONSTRAINT `fk_PRESTAMO_PERSONA1`
    FOREIGN KEY (`Responsable`)
    REFERENCES `Proyecto_sena`.`PERSONA` (`Documento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Proyecto_sena`.`CATEGORIA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Proyecto_sena`.`CATEGORIA` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`Id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Proyecto_sena`.`ELEMENTO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Proyecto_sena`.`ELEMENTO` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(150) NOT NULL,
  `Descripcion` VARCHAR(250) NOT NULL,
  `Serie` VARCHAR(50) NOT NULL,
  `Categoria` INT NOT NULL,
  `Material` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Id`),
  INDEX `fk_ELEMENTO_CATEGORIA_idx` (`Categoria` ASC),
  CONSTRAINT `fk_ELEMENTO_CATEGORIA`
    FOREIGN KEY (`Categoria`)
    REFERENCES `Proyecto_sena`.`CATEGORIA` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Proyecto_sena`.`UNIDADES`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Proyecto_sena`.`UNIDADES` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `Tipo` ENUM('Cantidad de sustancia', 'Intensidad de electricidad', 'Intensidad luminosa', 'Longitud', 'Masa', 'Otra') NOT NULL,
  `Nombre` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`Id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Proyecto_sena`.`MARCA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Proyecto_sena`.`MARCA` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`Id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Proyecto_sena`.`KIT`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Proyecto_sena`.`KIT` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(50) NOT NULL,
  `Descripcion` VARCHAR(200) NOT NULL,
  `Placa` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`Id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Proyecto_sena`.`ITEMS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Proyecto_sena`.`ITEMS` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `Placa` VARCHAR(30) NOT NULL,
  `Descripcion` VARCHAR(200) NOT NULL,
  `Costo` DOUBLE NOT NULL,
  `Ubicacion` VARCHAR(80) NOT NULL,
  `Imagen` VARCHAR(60) NOT NULL,
  `Elemento` INT NOT NULL,
  `Marca` INT NOT NULL,
  `Kit` INT NULL,
  `Unidades` INT NOT NULL,
  `Estado` ENUM('Activo', 'Inactivo') NOT NULL,
  PRIMARY KEY (`Id`),
  INDEX `fk_ITEMS_ELEMENTO1_idx` (`Elemento` ASC),
  INDEX `fk_ITEMS_UNIDADES1_idx` (`Unidades` ASC),
  INDEX `fk_ITEMS_MARCA1_idx` (`Marca` ASC),
  INDEX `fk_ITEMS_KIT2_idx` (`Kit` ASC),
  CONSTRAINT `fk_ITEMS_ELEMENTO1`
    FOREIGN KEY (`Elemento`)
    REFERENCES `Proyecto_sena`.`ELEMENTO` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ITEMS_UNIDADES1`
    FOREIGN KEY (`Unidades`)
    REFERENCES `Proyecto_sena`.`UNIDADES` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ITEMS_MARCA1`
    FOREIGN KEY (`Marca`)
    REFERENCES `Proyecto_sena`.`MARCA` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ITEMS_KIT2`
    FOREIGN KEY (`Kit`)
    REFERENCES `Proyecto_sena`.`KIT` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Proyecto_sena`.`SANCIONES`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Proyecto_sena`.`SANCIONES` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `Tipo` ENUM('Perdida', 'Daño') NOT NULL,
  `Descripcion` TEXT NOT NULL,
  `Prestamo` INT NOT NULL,
  `Estado` ENUM('Activo', 'Inactivo') NOT NULL,
  PRIMARY KEY (`Id`),
  INDEX `fk_Sanciones_PRESTAMO1_idx` (`Prestamo` ASC),
  CONSTRAINT `fk_Sanciones_PRESTAMO1`
    FOREIGN KEY (`Prestamo`)
    REFERENCES `Proyecto_sena`.`PRESTAMO` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Proyecto_sena`.`DETALLEPRESTAMO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Proyecto_sena`.`DETALLEPRESTAMO` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `Observaciones` VARCHAR(200) NOT NULL,
  `Items` INT NULL,
  `Prestamo` INT NOT NULL,
  `Kit` INT NULL,
  INDEX `fk_ITEMS_has_PRESTAMO_PRESTAMO1_idx` (`Prestamo` ASC),
  INDEX `fk_ITEMS_has_PRESTAMO_ITEMS1_idx` (`Items` ASC),
  PRIMARY KEY (`Id`),
  INDEX `fk_DETALLEPRESTAMO_KIT1_idx` (`Kit` ASC),
  CONSTRAINT `fk_ITEMS_has_PRESTAMO_ITEMS1`
    FOREIGN KEY (`Items`)
    REFERENCES `Proyecto_sena`.`ITEMS` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ITEMS_has_PRESTAMO_PRESTAMO1`
    FOREIGN KEY (`Prestamo`)
    REFERENCES `Proyecto_sena`.`PRESTAMO` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_DETALLEPRESTAMO_KIT1`
    FOREIGN KEY (`Kit`)
    REFERENCES `Proyecto_sena`.`KIT` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Proyecto_sena`.`MAQUINARIA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Proyecto_sena`.`MAQUINARIA` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `Placa` VARCHAR(45) NOT NULL,
  `Tipo` ENUM('..') NOT NULL,
  `Fabricante` ENUM('Caterpila', 'Otros') NOT NULL,
  `Modelo` VARCHAR(50) NOT NULL,
  `Combustible` VARCHAR(45) NOT NULL,
  `Ubicacion` VARCHAR(100) NOT NULL,
  `Seccion` VARCHAR(45) NOT NULL,
  `CaracteristicasGenerales` TEXT NOT NULL,
  `CaracteristicasTecnicas` TEXT NOT NULL,
  `Funcion` TEXT NOT NULL,
  `Foto` VARCHAR(60) NOT NULL,
  PRIMARY KEY (`Id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Proyecto_sena`.`MANTENIMIENTO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Proyecto_sena`.`MANTENIMIENTO` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `Maquinaria` INT NOT NULL,
  `FechaInicio` DATETIME NOT NULL,
  `FechaFin` DATETIME NULL,
  `Descripcion` VARCHAR(45) NOT NULL,
  `Estado` ENUM('Activo', 'Inactivo') NOT NULL,
  PRIMARY KEY (`Id`),
  INDEX `fk_Mantenimiento_MAQUINARIA1_idx` (`Maquinaria` ASC),
  CONSTRAINT `fk_Mantenimiento_MAQUINARIA1`
    FOREIGN KEY (`Maquinaria`)
    REFERENCES `Proyecto_sena`.`MAQUINARIA` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Proyecto_sena`.`Elementos_Mantenimiento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Proyecto_sena`.`Elementos_Mantenimiento` (
  `Elemento` INT NOT NULL,
  `Mantenimiento` INT NOT NULL,
  INDEX `fk_Mantenimiento_has_ELEMENTO_ELEMENTO1_idx` (`Elemento` ASC),
  INDEX `fk_Mantenimiento_has_ELEMENTO_Mantenimiento1_idx` (`Mantenimiento` ASC),
  CONSTRAINT `fk_Mantenimiento_has_ELEMENTO_ELEMENTO1`
    FOREIGN KEY (`Elemento`)
    REFERENCES `Proyecto_sena`.`ELEMENTO` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Mantenimiento_has_ELEMENTO_Mantenimiento1`
    FOREIGN KEY (`Mantenimiento`)
    REFERENCES `Proyecto_sena`.`MANTENIMIENTO` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
